site_name: bert-vits2 合成效果对比 vits

theme:
  name: material
  features:
    - content.tabs

nav:
  - vits合成不同数据集对比: index.md
  # 在这里添加更多页面，如果需要

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lunar333/vits-japanese-finetune.git