site_name: 个人算法博客

theme:
  name: material
  features:
    - content.tabs

nav:
  - 二分搜索: 二分搜索.md
  - 双指针题目: 双指针题目.md
  - 滑动窗口题目: 滑动窗口题目.md
  # 在这里添加更多页面，如果需要

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: www.1434544232.online