name: publish site

on: 
  push: 
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs: 
  deploy:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 版本
    steps:
      - uses: actions/checkout@v3 # 使用 v3 版本
      - uses: actions/setup-python@v4 # 使用 v4 版本
        with:
          python-version: '3.x' # 安装 Python 3.x 版本
      - run: pip install mkdocs-material # 安装 MkDocs 和 Material 主题
      - run: mkdocs build # 构建站点
      - run: cp CNAME site/ # 将 CNAME 文件复制到 site 目录中
      - run: mkdocs gh-deploy --force # 部署到 gh-pages 分支