name: Publish MkDocs site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Build site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force

      - name: Configure Git
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git config --global credential.helper store

      - name: Add CNAME to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/lunar333/Asahi-blog.git out
          cd out
          git checkout gh-pages
          echo "www.example.com" > CNAME  # 手动创建 CNAME 文件
          git add CNAME
          git commit -m "Add CNAME file"
          git push origin gh-pages